=== JuanjoAJ/Lenguaje-de-Marcas/T5  - YAML/validacion.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT asignatura (titulo+, tema+)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT tema (lecciones+) >
<!ATTLIST tema titulo CDATA #REQUIRED>
<!ELEMENT lecciones (leccion+)>
<!ELEMENT leccion (#PCDATA)>
<!ATTLIST leccion titulo CDATA #REQUIRED>

=== JuanjoAJ/Lenguaje-de-Marcas/T5  - YAML/temario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE asignatura SYSTEM "./validacion.dtd">
<asignatura>
    <titulo> Lenguaje de marcas</titulo>
    <tema titulo="XML">
        <lecciones>
                <leccion titulo="Introduccion">Introducción a los sistemas XML</leccion>
                <leccion titulo="Estructura">Estructuras de un fichero XML</leccion>
                <leccion titulo="Usos">Usos que tienen los ficheros XML</leccion>
        </lecciones>
        </tema>
    <tema titulo="HTML">
            <lecciones>
                <leccion titulo="Introduccion">Introducción a HTML</leccion>
                <leccion titulo="Etiquetas">Definición y uso de cada una de las etiqutas</leccion>
                <leccion titulo="CSS">Usos de CSS sobre HTML</leccion>
            </lecciones>
    </tema>
    <tema titulo="Dinamismo">
            <lecciones>
                <leccion titulo="Introduccion">Introducción a JS</leccion>
                <leccion titulo="DOM">Definición y uso de DOM</leccion>
                <leccion titulo="JSON">Creación de objetos en JS</leccion>
            </lecciones>
    </tema>
</asignatura>
